name: publish-nuget-package
on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine package version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - name: Display package version
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Package
        run: dotnet pack Hackney.Shared.Activity -p:PackageVersion=$SEMVER --configuration Release
      - name: Publish the Package
        run: |
          cd /Hackney.Shared.Activity/bin/Release
          dotnet nuget push Hackney.Shared.Activity.*.nupkg -s https://nuget.pkg.github.com/LBHackney-IT/index.json --api-key ${{secrets.NUGET_KEY }} Hackney.Shared.Activity.*/*.nupkg